"""arch311-rip: turn the user's own Windows 3.11 floppies into assets the Linux ports load.

    python3 -m arch311rip DISK1.IMG ... DISK6.IMG -o ~/.local/share/arch311
    python3 -m arch311rip /path/to/folder/with/images -o OUT
    python3 -m arch311rip /mnt/oldpc/WINDOWS -o OUT      (an installed WINDOWS dir works too)

Nothing produced here may be committed to the repository (see docs/LEGAL.md).
"""
import argparse
import hashlib
import json
import os
import sys

from . import fat12, kwaj, ne, resources as R

FONT_EXT = (".FON", ".FNT")


def _safe(name):
    return "".join(c if c.isalnum() or c in "._-" else "_" for c in str(name))


def gather(inputs, log):
    """Yield (filename, bytes, origin) for every file from images / dirs."""
    for inp in inputs:
        if os.path.isdir(inp):
            for root, _dirs, files in os.walk(inp):
                for f in sorted(files):
                    p = os.path.join(root, f)
                    if f.upper().endswith((".IMG", ".IMA", ".VFD")):
                        yield from gather([p], log)
                    else:
                        with open(p, "rb") as fh:
                            yield f.upper(), fh.read(), os.path.relpath(p, inp)
        else:
            with open(inp, "rb") as fh:
                data = fh.read()
            try:
                img = fat12.Fat(data)
            except ValueError:
                yield os.path.basename(inp).upper(), data, inp
                continue
            n = 0
            for path, blob in img.files():
                n += 1
                yield path.split("/")[-1].upper(), blob, "%s:%s" % (os.path.basename(inp), path)
            log("  %s: %d files" % (os.path.basename(inp), n))


def expand_all(inputs, files_dir, log):
    os.makedirs(files_dir, exist_ok=True)
    manifest = {}
    for name, blob, origin in gather(inputs, log):
        if kwaj.is_compressed(blob):
            try:
                blob, real = kwaj.expand(blob)
            except kwaj.FormatError as e:
                log("  !! %s: %s" % (name, e))
                continue
            if real:
                name = real.upper().rstrip(".")
                if name == "WINVER":
                    name = "WINVER.EXE"
        with open(os.path.join(files_dir, name), "wb") as fh:
            fh.write(blob)
        manifest[name] = {"origin": origin, "size": len(blob),
                          "sha256": hashlib.sha256(blob).hexdigest()}
    return manifest


def _write(path, data, mode="wb"):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, mode) as fh:
        fh.write(data)


def _json(path, obj):
    _write(path, json.dumps(obj, indent=1, ensure_ascii=False), "w")


def rip_module(path, outdir, png=True):
    with open(path, "rb") as fh:
        data = fh.read()
    m = ne.NE(data)
    base = os.path.join(outdir, os.path.basename(path).upper())
    res = m.resources()
    summary = {
        "file": os.path.basename(path).upper(), "module": m.module_name,
        "description": m.description, "is_dll": m.is_dll,
        "expected_windows": "%d.%02d" % (m.expver >> 8, m.expver & 0xFF),
        "imports": m.imports,
        "segments": [{k: s[k] for k in ("index", "kind", "length", "flags", "has_relocs")}
                     for s in m.segments],
        "exports": {str(k): v for k, v in sorted({**m.resident_names, **m.nonresident_names}.items())},
        "resources": {},
    }
    icons = {r.name: r.data for r in res if r.type == 3}
    cursors = {r.name: r.data for r in res if r.type == 1}
    strings = {}
    rc = ["// Resource script decompiled from the user's own %s" % summary["file"],
          "// Generated by arch311-rip. Do not commit.", ""]
    for r in res:
        tn = r.type_name
        summary["resources"].setdefault(tn, []).append(r.name)
        rid = _safe(r.name)
        try:
            if r.type == 2:
                bmp = R.dib_to_bmp(r.data)
                _write("%s/bitmap/%s.bmp" % (base, rid), bmp)
                if png:
                    p = R.image_to_png(bmp, "bmp")
                    if p:
                        _write("%s/bitmap/%s.png" % (base, rid), p)
            elif r.type in (14, 12):
                cur = r.type == 12
                blob = R.build_group(r.data, cursors if cur else icons, cursor=cur)
                kind = "cur" if cur else "ico"
                sub = "cursor" if cur else "icon"
                _write("%s/%s/%s.%s" % (base, sub, rid, kind), blob)
                if png:
                    p = R.image_to_png(blob, kind)
                    if p:
                        _write("%s/%s/%s.png" % (base, sub, rid), p)
            elif r.type == 4:
                items = R.menu(r.data)
                _json("%s/menu/%s.json" % (base, rid), items)
                rc += [R.menu_rc(r.name, items), ""]
            elif r.type == 5:
                d = R.dialog(r.data)
                _json("%s/dialog/%s.json" % (base, rid), d)
                rc += [R.dialog_rc(r.name, d), ""]
            elif r.type == 6:
                strings.update(R.string_block(r.name, r.data))
            elif r.type == 9:
                _json("%s/accel/%s.json" % (base, rid), R.accelerators(r.data))
            elif r.type == 16:
                _json("%s/version.json" % base, R.version(r.data))
            elif r.type == 8:
                _write("%s/font/%s.fnt" % (base, rid), r.data)
                _json("%s/font/%s.json" % (base, rid), R.fnt_info(r.data))
                if png:
                    p = R.fnt_sheet_png(r.data)
                    if p:
                        _write("%s/font/%s.png" % (base, rid), p)
            elif r.type in (1, 3):
                pass  # emitted via their groups
            else:
                _write("%s/raw/%s_%s.bin" % (base, _safe(tn), rid), r.data)
        except Exception as e:  # keep going; record the failure
            summary.setdefault("errors", []).append("%s %s: %s" % (tn, r.name, e))
            _write("%s/raw/%s_%s.bin" % (base, _safe(tn), rid), r.data)
    if strings:
        _json("%s/strings.json" % base, {str(k): v for k, v in sorted(strings.items())})
        rc += ["STRINGTABLE", "BEGIN"]
        rc += ['    %d, "%s"' % (k, v.replace('"', '""')) for k, v in sorted(strings.items())]
        rc += ["END", ""]
    _write("%s/%s.rc" % (base, summary["file"].split(".")[0]), "\n".join(rc), "w")
    _json("%s/module.json" % base, summary)
    return summary


def main(argv=None):
    ap = argparse.ArgumentParser(prog="arch311-rip", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+", help="floppy images, folders of images, or a WINDOWS dir")
    ap.add_argument("-o", "--out", default=os.path.expanduser("~/.local/share/arch311"))
    ap.add_argument("--no-png", action="store_true", help="skip PNG previews (no Pillow needed)")
    ap.add_argument("-q", "--quiet", action="store_true")
    a = ap.parse_args(argv)
    log = (lambda *_: None) if a.quiet else (lambda s: print(s, file=sys.stderr))

    files_dir = os.path.join(a.out, "files")
    log("expanding media ...")
    manifest = expand_all(a.inputs, files_dir, log)
    log("  %d files expanded" % len(manifest))

    log("ripping NE resources ...")
    catalog = {}
    for name in sorted(manifest):
        p = os.path.join(files_dir, name)
        try:
            s = rip_module(p, os.path.join(a.out, "res"), png=not a.no_png)
        except ne.NotNE:
            continue
        except Exception as e:
            log("  !! %s: %s" % (name, e))
            continue
        catalog[name] = {"module": s["module"], "description": s["description"],
                         "dll": s["is_dll"],
                         "resources": {k: len(v) for k, v in s["resources"].items()},
                         "errors": len(s.get("errors", []))}
    _json(os.path.join(a.out, "manifest.json"), manifest)
    _json(os.path.join(a.out, "catalog.json"), catalog)
    nerr = sum(c["errors"] for c in catalog.values())
    log("  %d NE modules ripped, %d resource errors" % (len(catalog), nerr))
    log("done -> %s" % a.out)
    return 0 if nerr == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
